hivedb/hive

lib/src/backend/vm/backend_manager.dart

I was using the deleteBoxFromDisk() to delete a box without opening it because i made changes to the model. The problem was however that the .hivec file didn't exist and this made my app crash.

vm deleteBox should check if file exists before deleting it

---

lib/src/registry/type_registry_impl.dart

I was getting the error ```There is already a TypeAdapter for typeId 58``` when in reality I should have been getting the error ```There is already a TypeAdapter for typeId 26```. 
This PR makes sure the error developers see is accurate and uses the correct typeId, by taking the reserved type ids into account.

Fixed error message for duplicate typeIds

---

hive_generator/lib/src/type_adapter_generator.dart

Fixes #226. Tested using the forked repository as dependency in pubspec.yaml. Not sure how to use flutter test to see if generated TypeAdapters are comparable.

add hash code and == operator overrides to TypeAdapterGenerator

---

hive_generator/lib/src/class_builder.dart

Fixes #245 
This PR tweaks the generated code so it plays well with generics.
type | before | after
---|---|---
default | `as TypeWithGeneric` | `as TypeWithGeneric<T>`
`Iterable` | `.cast<TypeWithGeneric>()` | `.cast<TypeWithGeneric<T>>()`
`Map` | `.cast<TypeWithGeneric, OtherType>()` | `.cast<TypeWithGeneric<T>, OtherType<S>>()`

Cast to specific type

---

hive_flutter/pubspec.yaml

`path` 1.7.0 was released on 13.04.2020 and new versions of `flutter` [1.18.0-6.0.pre.99 in my case] depend on 1.7.0.
So the current version restriction is the blocker for everyone naive enough to run `flutter upgrade` these days:
```
Because every version of flutter_test from sdk depends on path 1.7.0 and hive_flutter 0.3.0+2 depends on path >=1.6.0 <1.7.0, flutter_test from sdk is incompatible with hive_flutter 0.3.0+2.
And because no versions of hive_flutter match >0.3.0+2 <0.4.0, flutter_test from sdk is incompatible with hive_flutter ^0.3.0+2.
So, because app depends on both hive_flutter ^0.3.0+2 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because app depends on both hive_flutter ^0.3.0+2 and flutter_test any from sdk, version solving failed.)
``` …

Ease up path dependency

---

hive/lib/src/backend/js/backend_manager.dart
hive/lib/src/backend/storage_backend.dart
hive/lib/src/backend/stub/backend_manager.dart
hive/lib/src/backend/vm/backend_manager.dart
hive/lib/src/hive.dart
hive/lib/src/hive_impl.dart
hive/test/tests/hive_impl_test.dart

Adding a method to check if a box exists given its `name` and an optional `path`. This method is useful in case of migrations where you want to proceed only if a certain box exists.

Adds boxExists method to Hive

---

hive_generator/lib/src/type_adapter_generator.dart

See issues https://github.com/hivedb/hive/issues/361 and https://github.com/hivedb/hive/issues/364
Chanced check statement with OR conditional to allow for ElementKind.ENUM

Fixing issue with enums: Error running TypeAdapterGenerator

---

hive_generator/lib/src/class_builder.dart
hive_generator/lib/src/enum_builder.dart
hive_generator/lib/src/type_adapter_generator.dart

Before:
```dart
@override
final typeId = 1;
@override
XXXModel read(BinaryReader reader) {
var numOfFields = reader.readByte();
var fields = <int, dynamic>{
for (var i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
};
```
After:
```dart
@override
final int typeId = 1;
@override
XXXModel read(BinaryReader reader) {
final int numOfFields = reader.readByte();
final Map<int, dynamic> fields = <int, dynamic>{
for (int i = 0; i < numOfFields; i++)
reader.readByte(): reader.read(),
};
```
And some format updates too.

Make generates code follow the analyzer's option

---

hive/lib/src/binary/binary_writer_impl.dart

`writeBoolList` method inside `binary_writer_impl.dart` is reserving `8 * length` bytes, where it should suffice to reserve only `length` bytes.
This change does not impact `readBoolList` of `BinaryReaderImpl`.

Remove extra byte reservation in writeBoolList

---

hive_flutter/example/README.md

The sample link which is mention is invalid 
so I have updated the sample link.

updated hive sample link

---

hive_generator/pubspec.yaml

The latest version of `build_runner` depends on `build` 2.0.0 (the null-safe version). That conflicts with the current constraint on `build` in `hive_flutter`. This PR relaxes the constraint so `build` 2.0.0 is allowed.
Fixes #597.
EDIT: Oops, did a wrong `git commit --amend`, will try to fix 😅
EDIT2: Fixed :)

Relax build dependency constraint for hive_generator

---

hive_flutter/lib/hive_flutter.dart

We always need hive when using hive_flutter, so:
This PR eliminates the need of the additional hive import when using hive_flutter by exporting hive in hive_flutter.

Export hive from hive_flutter

---

hive_generator/lib/src/class_builder.dart

Resolves error "The argument type 'HiveList<T>?' can't be assigned to the parameter type 'HiveList<T>'.
Closes issue #644.

Ensure HiveLists are treated as non-nullable in hive_generator

---

hive/lib/src/hive_impl.dart

If Box.openBox raises an exception to due being corrupt or having an unknown type, the reference to the open file is dropped. The result of this is that on Windows, it is not possible to delete the corrupted box as .close() can't be called so Windows thinks the file is still in use.
This saves the reference to the open file before calling initialize() rather than afterwards.

Don't loose track of box objects if init crashes

---

hive/lib/src/backend/js/storage_backend_js.dart
hive/lib/src/backend/storage_backend.dart
hive/lib/src/backend/storage_backend_memory.dart
hive/lib/src/backend/vm/storage_backend_vm.dart
hive/lib/src/box/box_base.dart
hive/lib/src/box/box_base_impl.dart
hive/lib/src/box/box_impl.dart
hive/lib/src/box/lazy_box_impl.dart

This PR adds a flush method to boxes to be able to manually flush them to the disk. If utilized correctly, this would solve #263

feat: Add flush method to boxes

---

hive/lib/src/backend/vm/storage_backend_vm.dart
hive/lib/src/binary/binary_reader_impl.dart
hive/test/tests/backend/vm/storage_backend_vm_test.dart
hive/test/tests/binary/binary_reader_test.dart

Hello, this PR prevents the occurence of the well known `HiveError: This should not happen. Please open an issue on GitHub.` error moreover it fixes these boxes if the box becomes **unrecoverable**.
This PR has two commits:
1. prevents this error from happening (+ tests)
2. recovers box if error already happened (+ tests)
The problem happens when Hive tries to open a corrupted box which is **recoverable** however unfortunately the recover process is working incorrectly and if Hive tries to put something in the **_"recovered"_** box then the box becomes **unrecoverable** but it can be used for write / read until the box is closed and whenever Hive wants open this **unrecoverable** box the above error happens.
Demonstration example:
```dart
import 'dart:io';
import 'dart:typed_data';
import …
```

Fix: This should not happen. Please open an issue on GitHub.

---

hive/lib/src/hive_impl.dart

#846 fix should be rerolled.
```dart
_boxes[name] = newBox;
await newBox.initialize();
```
`_boxes` can contain a box which isn't initialized so it is possible that `isBoxOpen(name)` return `true` and program can acquire this uninitialized box which can lead serios problems for example `box.put` called.
Imagine the following situation:
```dart
var box = Hive.openBox('box');
var sameBox = Hive.openBox('box');
```
In this case `sameBox` can be referenced before it's initialized. However this cannot be achieved so easily because we have to get the reference after `_boxes[name] = newBox;` and during `await newBox.initialize();` call ([and also after `_manager.open`](https://github.com/Jon-Salmon/hive/blob/afef78771ba61892a9f2d716abc203aa4e9ef20f/hive/lib/src/hive_impl.dart#L105)).
**There is …

Do not return uninitialized box

---

hive/lib/src/registry/type_registry_impl.dart
hive/test/tests/registry/type_registry_impl_test.dart

Let P be a super type and C its subtype.
In the current implementation, `TypeRegistryImpl.findAdapterForValue` always picks the first match for an adapter of C. This behavior is okay. However, when two type adapters, one for P and one for C got registered (first P and then C), then `TypeRegistryImpl.findAdapterForValue` will always return the adapter for P and never the more specific one for C.
This PR adjusts the behavior to first return an adapter that matches the **runtime type** of `value`. When no such adapter exists, then it falls back to how the current implementation behaves.
It also adds some tests for the new implementation.
Closes https://github.com/hivedb/hive/issues/880, closes https://github.com/hivedb/hive/issues/893 and maybe https://github.com/hivedb/hive/issues/821.
I am …

Support adapter type inheritance

---

hive/lib/src/hive_impl.dart

When initialization fails hive doesn't closes references to files so on some systems this causes issues when retry used alongside with retry logic (user tries to re-open the box) or because file is locked, os doesn't allows removing that file to fix broken boxes. This PR closes boxes if initialization fails.

fix: Close uninitialized boxes

---

hive/lib/src/binary/binary_reader_impl.dart
hive/lib/src/binary/binary_writer_impl.dart
hive/lib/src/binary/frame.dart
hive/lib/src/util/extensions.dart
hive/test/tests/binary/frame_test.dart

This PR adds support for using unicode keys using UTF-8 encoding. There will be no backwards compatibility issue because ASCII is compatible with UTF-8 encoding.
Closes #159, #717, #412, #84, #37

Support UTF-8 keys

---

hive_generator/pubspec.yaml

This PR is same as https://github.com/hivedb/hive/pull/858
Update Analyzer version `< 5.0.0`
Could someone merge this PR and release new version for hive_generator?

hive_generator: Update Analyzer version.

---

hive/lib/src/hive_impl.dart
hive/test/integration/hive_list_test.dart
hive/test/integration/hive_object_test.dart
hive/test/integration/integration.dart
hive/test/integration/put_many_strings_test.dart
hive/test/tests/object/hive_list_impl_test.dart

- remove need for manual `Hive.init()` call
- provide default backend manager
- fix most tests
Fixes: #967

fix: provide fallback backend manager

---

.github/workflows/test.yml
hive_flutter/lib/src/hive_extensions.dart
hive_flutter/pubspec.yaml

- expose `backendPreferrence` to Hive Flutter

chore: allow Hive backend preferrence in Flutter

---

hive/lib/src/hive_impl.dart
hive/test/integration/recovery_test.dart
hive/test/tests/frames.dart

Regression was caused in #956 (4dbcd76) where `HiveImpl` no longer
called `_registerDefaultAdapters`, assuming that it would happen in
`init`, which is not necessary for web.
Also remove `HiveImpl.debug` and `HiveImpl.test`.
`HiveImpl.test` was masking some odd legacy behavior in tests, so this
fixes the test.
`HiveImpl.debug` is not used anywhere, and its funcationality can be
accomplished using `init`

Fix Regression #977 - Web not registering DateTimeAdapter

---

hive/test/tests/crypto/aes_cbc_pkcs7_test.dart
hive/test/tests/crypto/aes_engine_test.dart

- migrate deprecated fast AES engine test to AES engine

chore: migrate deprecated fast AES test to AES engine

---

hive/lib/hive.dart
hive/lib/src/backend/js/native/backend_manager.dart
hive/lib/src/backend/js/native/storage_backend_js.dart
hive/lib/src/box_collection/box_collection.dart
hive/lib/src/box_collection/box_collection_indexed_db.dart
hive/lib/src/box_collection/box_collection_stub.dart
hive/lib/src/hive_impl.dart

- adds a direct web-only implementation of BoxCollections
- migrates the previous BoxCollections interface into an abstract
implementation
- the direct indexed DB calls on web significantly improve the response
time of transactions as the required Dart code to be executed is less than 25 % of the previous state
- as web is generally slow, this should improve the speed and make it
comparable to io-platforms
- behavior on io-platforms untouched
Please tell me whether you are okay with this implementation as it introduces more platform-specific code.

feat: improve web performance of BoxCollections

---

hive/lib/src/hive.dart
hive/lib/src/hive_impl.dart
hive/lib/src/registry/type_registry_impl.dart
hive/test/tests/hive_impl_test.dart

**READY**
NO
Makes the `clearAdapters` part of the public API.
When configuring integration tests one usually does the following:
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:my_app/main/main.dart' as app;
void main() {
IntegrationTestWidgetsFlutterBinding.ensureInitialized().framePolicy =
LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;
group('login', () {
setUp(app.main); // This setup registers the adapters.
testWidgets('unsuccessful when missing username', (tester) async {
// Some logic here.
});
testWidgets('unsuccessful when missing password', (tester) async {
// Some logic here.
});
});
}
```
However,  only the test that runs first succeeds since when the second test aims to `registerAdapter` a …

feat: made resetAdapters public

---

hive/lib/src/backend/vm/storage_backend_vm.dart
hive/lib/src/hive.dart
hive/lib/src/hive_impl.dart

This is somewhat of a workaround for an iOS issue we ran into. We use hive as the database for a chat application. To be able to show notifications when the app is in the background we use a Notification Service Extension and give the NSE access to the database, so that it can read the room names and such from the database. (We implemented a barebones hive reader in Swift for that.)
Since the database is only opened read only while the app is suspended and we only read data from it and immediately close it again, we don't really have any concurrency issues. However, iOS unconditionally kills your application if it has any lockfiles open in a directory, that another process could access. Since we share a container with the NSE, our app gets killed any time it is backgrounded. There might …

Allow users to disable lockfiles at their own risk

---

hive/lib/src/hive_impl.dart

Shouldn't this check be removed? 
https://github.com/hivedb/hive/blob/1451845d080007d8e9169798b4dda81cbd6c08fd/hive/lib/src/hive_impl.dart#L77-L78
Can't use `Future<BoxBase<E>> _openBox<E>` due to this with non-ASCII string. Fixed after removing this.

Allow non-ASCII box names

---

hive/lib/src/box_collection/box_collection.dart
hive/lib/src/box_collection/box_collection_stub.dart

Makes `useLocks` work also with collections.

Pass through useLocks parameter for hive collections

---

hive/lib/src/hive_impl.dart

Using `unawaited` provides more context about the purpose of not awaiting a future and it has no effects. In this commit, I simply deleted the "ignore lint" comment and wrapped the `remove` function in `unawaited`.
Following is the implementation of `unawaited` (from "dart:async" package):
```dart
/// Explicitly ignores a future.
///
/// Not all futures need to be awaited.
/// The Dart linter has an optional ["unawaited futures" lint](https://dart-lang.github.io/linter/lints/unawaited_futures.html)
/// which enforces that potential futures
/// (expressions with a static type of [Future] or `Future?`)
/// in asynchronous functions are handled *somehow*.
/// If a particular future value doesn't need to be awaited,
/// you can call `unawaited(...)` with it, which will avoid the lint,
/// …
```

chore: Use `unawaited` instead of ignoring the lint

---

hive/lib/src/box/change_notifier.dart

Resolves #1034
I have same issue using following code:
``` dart
final box = await Hive.openLazyBox('local');
await box.clear();
await box.close();
```

Prevent adding events to closed stream controller
