docs/write.md

It is missing a "is" on one sentence I red. This fix it

Add missing word on docs

---

hive/lib/hive.dart

Corrected typo

---

docs/generate_adapter.md

Update the docs with  the build command and add missing required dependency. Clears up #8

Update with info on build command

---

examples/counter/lib/main.dart
examples/counter/pubspec.yaml

Hello!
i would like to make a small improvement
the end result is this:
i hope this can be helpful in some way

improve counter app

---

hive_generator/lib/src/builder.dart
hive_generator/lib/src/class_builder.dart
hive_generator/lib/src/enum_builder.dart
hive_generator/lib/src/type_adapter_generator.dart

This introduces the feature discussed in #35.

feat: when deserializing types, use the constructor more extensively

---

docs/_sidebar.md
docs/examples.md

it is #31  , but against the master branch

add "examples" page on documentation

---

hive/README.md

The example as it stands doesn't compile.

Replace ; with , in README.md

---

example/lib/main.dart
example/lib/main.g.dart
lib/src/adapters/big_int_adapter.dart
lib/src/adapters/date_time_adapter.dart
lib/src/annotations/hive_type.dart
lib/src/hive_impl.dart
lib/src/registry/type_adapter.dart
lib/src/registry/type_registry.dart
lib/src/registry/type_registry_impl.dart
test/integration/hive_list_test.dart
test/integration/hive_object_test.dart
test/tests/registry/type_registry_impl_test.dart

See #163
Also see PR to generator: https://github.com/hivedb/hive_generator/pull/3

Added typeId property to HiveType (#163)

---

hive_generator/pubspec.yaml

bump dartx dependency version

---

hive_flutter/CHANGELOG.md
hive_flutter/lib/src/adapters/color_adapter.dart
hive_flutter/lib/src/adapters/time_adapter.dart
hive_flutter/pubspec.yaml
hive_flutter/test/adapters/color_adapter_test.dart
hive_flutter/test/adapters/time_adapter_test.dart
hive_flutter/test/mocks.dart

_(Copied from archived repository)_

Added color and time adapters and their appropriate tests

---

hive/lib/src/backend/js/storage_backend_js.dart
hive/test/tests/backend/js/storage_backend_js_test.dart

Fixes issue on Edge borwser

---

hive/lib/src/backend/js/backend_manager.dart
hive/test/tests/backend/js/backend_manager_test.dart

BackendManager.boxExists support for web

---

hive/lib/src/registry/type_registry.dart
hive/lib/src/registry/type_registry_impl.dart

This PR adds support for overriding internal and external adapters. This would be helpful in situations like #474

Adds support for overriding adapters

---

hive/lib/src/annotations/hive_field.dart
hive_generator/example/lib/person.dart
hive_generator/example/lib/person.g.dart
hive_generator/example/pubspec.yaml
hive_generator/lib/src/builder.dart
hive_generator/lib/src/enum_builder.dart
hive_generator/lib/src/type_adapter_generator.dart

Adds defaultValue argument to HiveField

---

hive_flutter/lib/src/hive_extensions.dart
hive_flutter/pubspec.yaml

- Updated null safe dependencies
- Updated null safety check in hive_extensions

Null safety fixes

---

hive/CHANGELOG.md
hive_generator/lib/src/builder.dart
hive_generator/lib/src/class_builder.dart
hive_generator/lib/src/enum_builder.dart
hive_generator/lib/src/helper.dart
hive_generator/pubspec.yaml

Migrate hive_generator dependencies to null-safety

---

hive/lib/src/binary/binary_reader_impl.dart

Introduced in fa875cc and 806c6ac

binary_reader: Fix regression where lists are no longer growable

---

.github/workflows/test.yml
hive_flutter/CHANGELOG.md
hive_flutter/analysis_options.yaml
hive_flutter/lib/adapters.dart
hive_flutter/lib/src/adapters/color_adapter.dart
hive_flutter/lib/src/adapters/time_adapter.dart
hive_flutter/lib/src/watch_box_builder.dart
hive_flutter/pubspec.yaml
hive_flutter/test/adapters/color_adapter_test.dart
hive_flutter/test/adapters/time_adapter_test.dart

Includes #698 and
- Minor linter warning fixes
- CI improvements

Upgrade hive_flutter to v1.1.0

---

hive_generator/lib/src/type_adapter_generator.dart

I think the diff is enough as description.

Fix check's bad condition in hive generator

---

hive_generator/pubspec.yaml

Fixes #725
Just updated hive_generator dependencies

Updated hive_generator dependencies

---

hive_generator/pubspec.yaml

Update analyzer to version < 4.0.0
Fixed #857

Updated hive_generator analyzer dependency

---

hive/analysis_options.yaml
hive/lib/src/backend/js/storage_backend_js.dart
hive/lib/src/backend/vm/storage_backend_vm.dart
hive/lib/src/binary/frame.dart
hive/lib/src/box/box_base.dart
hive/lib/src/box/lazy_box_impl.dart
hive/lib/src/hive.dart
hive/lib/src/hive_impl.dart
hive/lib/src/object/hive_object.dart
hive/pubspec.yaml
hive/test/integration/hive_list_test.dart
hive/test/integration/hive_object_test.dart
hive/test/integration/recovery_test.dart
hive/test/tests/backend/vm/backend_manager_test.dart
hive/test/tests/backend/vm/storage_backend_vm_test.dart
hive/test/tests/box/box_base_test.dart
hive/test/tests/mocks.dart
hive/test/tests/object/hive_list_impl_test.dart
hive/test/tests/util/delegating_list_view_mixin_test.dart
hive_flutter/lib/hive_flutter.dart
hive_flutter/test/adapters/color_adapter_test.dart
hive_flutter/test/adapters/time_adapter_test.dart
hive_generator/lib/src/type_adapter_generator.dart

Change pedantic to linter and fix warnings

---

.gitignore
hive/.pubignore
hive/lib/hive.dart
hive/lib/src/backend/js/backend_manager.dart
hive/lib/src/backend/js/native/backend_manager.dart
hive/lib/src/backend/js/native/box_collection_indexed_db.dart
hive/lib/src/backend/js/native/storage_backend_js.dart
hive/lib/src/backend/storage_backend.dart
hive/lib/src/backend/stub/backend_manager.dart
hive/lib/src/backend/vm/backend_manager.dart
hive/lib/src/box_collection.dart
hive/lib/src/hive.dart
hive/lib/src/hive_impl.dart
hive/lib/src/object/hive_storage_backend_preference.dart
hive/test/integration/recovery_test.dart
hive/test/tests/backend/js/backend_manager_test.dart
hive/test/tests/backend/js/storage_backend_js_test.dart

Somehow reached at *not* making this a breaking change...
- exposes BoxCollection
- prepares to add additional web backends
Fixes: #939

Upstream FluffyBox patches

---

hive/lib/src/backend/js/native/storage_backend_js.dart

- do not delete entire database in case only one objectStore to be
deleted

fix: support collections in deleteFromDisk

---

hive/README.md

- add documentation and example on BoxCollections and Transactions into
Readme

feat: add documentation on BoxCollections

---

hive_flutter/.gitignore

- adds `.gitignore` for Hive Flutter

feat: add .gitignore

---

hive/lib/src/backend/js/web_worker/web_worker_interface.dart
hive/lib/src/box_collection/box_collection.dart
hive/lib/src/hive.dart
hive/lib/src/hive_impl.dart

- adds a helper class as key for the open boxes in order to store them
including the name of the collection

feat: store open boxes including collection

---

hive/lib/src/box_collection/box_collection.dart
hive/lib/src/hive_impl.dart

fix: missing TupleBoxKey for opening boxes

---

.github/workflows/test.yml
hive_generator/CHANGELOG.md
hive_generator/lib/src/builder.dart
hive_generator/lib/src/class_builder.dart
hive_generator/lib/src/enum_builder.dart
hive_generator/lib/src/helper.dart
hive_generator/lib/src/type_adapter_generator.dart
hive_generator/lib/src/type_helper.dart
hive_generator/pubspec.yaml

Update analyzer 5.0.0 or higher

fix(hive_generator): Apply analyzer 5.0.0 or higher

---

hive/lib/src/backend/vm/storage_backend_vm.dart
hive/lib/src/hive_impl.dart

- remove final marker from registry
- remove unwanted visible for testing
Fixes: #1162

fix: don't mark registry as final

---

hive/analysis_options.yaml
hive/lib/src/backend/vm/backend_manager.dart
hive/lib/src/box_collection/box_collection.dart
hive/lib/src/hive_impl.dart
hive/lib/src/io/buffered_file_writer.dart
hive/test/tests/common.dart

- removes duplicate init on iOS breaking directory structure

fix: Hive iOS init

---

hive/lib/src/hive_impl.dart

Leaving hanging Futures that can raise Exceptions like happens to be nasty, because they will not be caught by a try-catch higher up the callstack. They can only get caught by zone-level error handling, which is not great.
This is necessary for my [hive_multiisolate](https://github.com/TheCarpetMerchant/hive_multiisolate) package to function with 100% safety (hopefully).

Prevent non-catchable errors from occurring when opening a box

---

hive_generator/pubspec.yaml

Set analyzer to '>=5.12.0 <7.0.0', compatible with json_serializable.

chore: Set analyzer to ">=4.6.0 <7.0.0"
